# LambdaTest Configuration

# Project and folder configuration
project_id: "01KJ7X8SK67HFWS6Y7H0EB3JPZ"
folder_id: "01KJ7X9ABYFD6KVE567J77J945"

# Test Run configuration
assignee: 159705
environment_id: 7

# Test URL for automation
# test_url: "https://demo.lambdatestinternal.com"
