# LambdaTest Configuration

# Project and folder configuration
project_id: "01J5TJP26TJ07R2C1KGK08EJFH"
folder_id: "01J5TJP27DC7XGRXWKT2FXSZ2G"

# Test Run configuration
assignee: 874322
environment_id: 207445

# Test URL for automation
# test_url: "https://demo.lambdatestinternal.com"
